import { ActivityType, CategoryType } from '../types/guide';
import { 
  Moon, 
  Sunrise, 
  Briefcase, 
  Palette, 
  Compass, 
  Heart, 
  Users, 
  Smile, 
  Gamepad2, 
  Share2, 
  GraduationCap, 
  MapPin, 
  Coffee, 
  Utensils, 
  MoreHorizontal 
} from 'lucide-react';

export interface ActivityMetadata {
  type: ActivityType;
  label: string;
  category: CategoryType;
  icon: typeof Briefcase;
  badgeBg: string;
  badgeText: string;
  borderColor: string;
  defaultIsPointInTime: boolean;
  defaultDurationMinutes: number;
}

export const ACTIVITY_REGISTRY: Record<ActivityType, ActivityMetadata> = {
  sleep: {
    type: 'sleep',
    label: 'نوم وراحة',
    category: 'rest',
    icon: Moon,
    badgeBg: 'bg-indigo-50',
    badgeText: 'text-indigo-800',
    borderColor: 'border-indigo-200',
    defaultIsPointInTime: false,
    defaultDurationMinutes: 480, // 8h
  },
  wake_up: {
    type: 'wake_up',
    label: 'استيقاظ (Wake Up)',
    category: 'routine',
    icon: Sunrise,
    badgeBg: 'bg-amber-50',
    badgeText: 'text-amber-800',
    borderColor: 'border-amber-200',
    defaultIsPointInTime: true,
    defaultDurationMinutes: 0,
  },
  work: {
    type: 'work',
    label: 'شغل وجلسة عمل',
    category: 'deep_work',
    icon: Briefcase,
    badgeBg: 'bg-stone-900',
    badgeText: 'text-emerald-300',
    borderColor: 'border-stone-700',
    defaultIsPointInTime: false,
    defaultDurationMinutes: 180, // 3h
  },
  design: {
    type: 'design',
    label: 'تصميم (Design)',
    category: 'deep_work',
    icon: Palette,
    badgeBg: 'bg-emerald-50',
    badgeText: 'text-emerald-800',
    borderColor: 'border-emerald-200',
    defaultIsPointInTime: false,
    defaultDurationMinutes: 45,
  },
  prayer: {
    type: 'prayer',
    label: 'صلاة وذكر (Prayer)',
    category: 'routine',
    icon: Compass,
    badgeBg: 'bg-teal-50',
    badgeText: 'text-teal-800',
    borderColor: 'border-teal-200',
    defaultIsPointInTime: true,
    defaultDurationMinutes: 15,
  },
  suhaila: {
    type: 'suhaila',
    label: 'سهيلة (تواصل ووقت خاص)',
    category: 'social',
    icon: Heart,
    badgeBg: 'bg-rose-50',
    badgeText: 'text-rose-800',
    borderColor: 'border-rose-200',
    defaultIsPointInTime: false,
    defaultDurationMinutes: 45,
  },
  family: {
    type: 'family',
    label: 'وقت عائلي ومع الأهل',
    category: 'social',
    icon: Users,
    badgeBg: 'bg-amber-50',
    badgeText: 'text-amber-900',
    borderColor: 'border-amber-200',
    defaultIsPointInTime: false,
    defaultDurationMinutes: 60,
  },
  friends: {
    type: 'friends',
    label: 'أصحاب وتواصل',
    category: 'social',
    icon: Smile,
    badgeBg: 'bg-blue-50',
    badgeText: 'text-blue-800',
    borderColor: 'border-blue-200',
    defaultIsPointInTime: false,
    defaultDurationMinutes: 90,
  },
  gaming: {
    type: 'gaming',
    label: 'ألعاب وترفيه (Gaming)',
    category: 'unstructured',
    icon: Gamepad2,
    badgeBg: 'bg-purple-50',
    badgeText: 'text-purple-800',
    borderColor: 'border-purple-200',
    defaultIsPointInTime: false,
    defaultDurationMinutes: 60,
  },
  social_media: {
    type: 'social_media',
    label: 'سوشيال ميديا وتصفح',
    category: 'unstructured',
    icon: Share2,
    badgeBg: 'bg-sky-50',
    badgeText: 'text-sky-800',
    borderColor: 'border-sky-200',
    defaultIsPointInTime: false,
    defaultDurationMinutes: 30,
  },
  institute: {
    type: 'institute',
    label: 'المعهد ودراسة',
    category: 'institute',
    icon: GraduationCap,
    badgeBg: 'bg-violet-50',
    badgeText: 'text-violet-800',
    borderColor: 'border-violet-200',
    defaultIsPointInTime: false,
    defaultDurationMinutes: 180,
  },
  outing: {
    type: 'outing',
    label: 'مشوار أو خروجة',
    category: 'social',
    icon: MapPin,
    badgeBg: 'bg-orange-50',
    badgeText: 'text-orange-800',
    borderColor: 'border-orange-200',
    defaultIsPointInTime: false,
    defaultDurationMinutes: 120,
  },
  personal: {
    type: 'personal',
    label: 'وقت شخصي وروقان',
    category: 'rest',
    icon: Coffee,
    badgeBg: 'bg-stone-100',
    badgeText: 'text-stone-800',
    borderColor: 'border-stone-200',
    defaultIsPointInTime: false,
    defaultDurationMinutes: 45,
  },
  meal: {
    type: 'meal',
    label: 'فطار / غداء / شاي',
    category: 'health',
    icon: Utensils,
    badgeBg: 'bg-emerald-50',
    badgeText: 'text-emerald-900',
    borderColor: 'border-emerald-200',
    defaultIsPointInTime: false,
    defaultDurationMinutes: 30,
  },
  other: {
    type: 'other',
    label: 'نشاط آخر',
    category: 'unstructured',
    icon: MoreHorizontal,
    badgeBg: 'bg-stone-50',
    badgeText: 'text-stone-700',
    borderColor: 'border-stone-200',
    defaultIsPointInTime: false,
    defaultDurationMinutes: 30,
  },
};

export const QUICK_ACTIVITY_CHIPS: { type: ActivityType; title: string }[] = [
  { type: 'wake_up', title: 'استيقاظ (Wake Up)' },
  { type: 'meal', title: 'فطار وشاي' },
  { type: 'family', title: 'وقت مع الأهل' },
  { type: 'work', title: 'بدء الشغل' },
  { type: 'design', title: 'تصميم جديد' },
  { type: 'prayer', title: 'صلاة' },
  { type: 'personal', title: 'وقت شخصي' },
  { type: 'suhaila', title: 'تواصل مع سهيلة' },
  { type: 'gaming', title: 'ألعاب وراحة' },
  { type: 'outing', title: 'مشوار / خروجة' },
];
